name: dart_code_metrics
version: 6.0.2
description: Software analytics tool that helps developers analyse and improve software quality.
repository: https://github.com/anusii/dart-code-metrics

environment:
  sdk: '>=3.2.3 <4.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ^7.3.0
  analyzer_plugin: ^0.11.0
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.18.0
  crypto: ^3.0.0
  dart_code_metrics_presets: ^2.15.0
  file: ^7.0.0
  glob: ^2.0.1
  html: '>=0.15.0 <1.0.0'
  http: ^1.0.0
  meta: ^1.7.0
  path: ^1.8.0
  platform: ^3.1.0 # overridden for lowest versions compatibility
  pub_updater: ^0.5.0
  source_span: ^1.8.0
  uuid: ^4.4.2
  xml: '>=5.3.0 <7.0.0'
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  intl: ^0.20.2
  lints: ^5.1.1
  mocktail: ^1.0.4
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
